workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      node: 22
      cocoapods: default
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install @capacitor/core @capacitor/cli @capacitor/ios

      - name: Build web app
        script: |
          npm run build

      - name: Copy web assets to iOS
        script: |
          npx cap copy ios

    artifacts:
      - ios/App/build/Build/Products/Release-iphoneos/*.ipa
      - /Users/builder/.npm/_logs/*.log
